from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import click
import requests
from rich.console import Console
from rich.prompt import Confirm, Prompt

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from cli.lib.config import (
    ACTIVE_SITE_FILE,
    SITES_DIR,
    ensure_project_structure,
    get_active_site,
    list_sites,
    save_local_config,
    set_active_site,
    site_name_from_url,
)
from setup.build_config import DEFAULT_DEPLOY_ORDER

console = Console()


def _decode_pair_code(code: str) -> tuple[str, str]:
    """Decode a hex pairing code into (site_url, nonce).

    The code is hex(JSON{"u": site_url, "n": nonce}) and is generated by
    the WordPress admin panel under WP Remote Shell → CLI Pairing Code.
    """
    try:
        bundle = json.loads(bytes.fromhex(code.strip()).decode("utf-8"))
        url = bundle["u"].rstrip("/")
        nonce = bundle["n"]
        if not url or not nonce:
            raise ValueError("Empty fields")
        return url, nonce
    except Exception:
        raise click.ClickException(
            "Invalid pairing code. Copy the full code shown in WordPress → WP Remote Shell → CLI Pairing Code."
        )


@click.command("pair")
@click.argument("code")
@click.option("--project", "project_path", default=None, help="Local project folder (prompted if omitted).")
@click.option("--pin", default=None, help="Circuit-breaker PIN (prompted if omitted).")
def pair_command(code: str, project_path: str | None, pin: str | None) -> None:
    """Connect this CLI to a WordPress site using the hex code from the WP admin panel.

    Copy the pairing code from WordPress → WP Remote Shell → CLI Pairing Code,
    then run:  python cli/wrs.py pair <code>
    """
    site_url, nonce = _decode_pair_code(code)
    site_name = site_name_from_url(site_url)

    console.print(f"Pairing with [bold]{site_url}[/bold]  (site: [bold]{site_name}[/bold])")

    # Call the plugin's pairing endpoint — no HMAC needed; the nonce is the auth.
    pair_endpoint = f"{site_url}/wp-json/wrs/v1/connect/pair"
    try:
        resp = requests.post(pair_endpoint, json={"nonce": nonce}, timeout=30)
    except requests.RequestException as exc:
        raise click.ClickException(f"Could not reach {site_url}: {exc}") from exc

    if resp.status_code == 429:
        raise click.ClickException("Too many pairing attempts from this IP. Wait 15 minutes and try again.")
    if resp.status_code == 403:
        raise click.ClickException(
            "Pairing code is invalid or has already been used. Generate a new one in the WP admin panel."
        )
    if not resp.ok:
        try:
            msg = resp.json().get("message") or resp.text[:200]
        except Exception:
            msg = resp.text[:200]
        raise click.ClickException(f"Pairing failed ({resp.status_code}): {msg}")

    data = resp.json()
    if not data.get("paired"):
        raise click.ClickException(f"Pairing rejected: {data.get('message', 'unknown error')}")

    token = data["token"]
    returned_page_mode = data.get("page_mode", "html")
    returned_css_mode = data.get("css_mode", "inline")
    modules: dict[str, bool] = {k: bool(v) for k, v in data.get("modules", {}).items()}

    # Ask for the two items the server can't know.
    default_project = str((Path.home() / "wrs-sites" / site_name).resolve())
    if not project_path:
        project_path = Prompt.ask("Local project path", default=default_project).strip()
    project_path = str(Path(project_path).expanduser().resolve())

    if not pin:
        while True:
            pin = Prompt.ask("Circuit-breaker reset PIN (digits only, 6+ chars)", password=True).strip()
            if not (pin.isdigit() and len(pin) >= 6):
                console.print("[red]Use digits only, at least 6 characters.[/red]")
                continue
            confirm = Prompt.ask("Confirm PIN", password=True).strip()
            if pin != confirm:
                console.print("[red]PINs did not match.[/red]")
                continue
            break

    local_config: dict = {
        "site_name": site_name,
        "site_url": site_url,
        "token": token,
        "project_path": project_path,
        "page_mode": returned_page_mode,
        "css_mode": returned_css_mode,
        "default_status": "draft",
        "ai_cli_command": "",
        "ai_operation_mode": "assisted",
        "wc_consumer_key": "",
        "wc_consumer_secret": "",
        "deploy_order": DEFAULT_DEPLOY_ORDER,
        "modules": modules,
        "circuit_breaker": {
            "consecutive_failure_threshold": 3,
            "failure_window_minutes": 10,
            "partial_counts_as_failure": True,
            "human_pin_to_reset": True,
            "human_pin": pin,
            "block_reads_when_open": False,
        },
        "checkpoint": {"auto_checkpoint": True, "local_copy": True},
        "reconcile": {"auto_before_ai": False},
    }

    ensure_project_structure(project_path)
    save_local_config(site_name, local_config)
    set_active_site(site_name)

    console.print(f"\n[green]Paired successfully.[/green]")
    console.print(f"Site:    {site_name}")
    console.print(f"Project: {project_path}")
    console.print("Run [bold]python cli/wrs.py status[/bold] to confirm the connection.")


@click.command("disconnect")
@click.option("--site", "site_name", default=None, help="Site to disconnect (default: active site).")
@click.option(
    "--revoke",
    is_flag=True,
    default=False,
    help="Also clear the token on the server and disable the plugin API. Cannot be undone remotely.",
)
def disconnect_command(site_name: str | None, revoke: bool) -> None:
    """Remove local credentials for a site.

    Without --revoke this only removes the local config files; the server token
    remains valid (useful if you want to re-pair on this machine later).

    With --revoke the token is cleared server-side too, making the server
    unreachable by any CLI until you re-run the wizard or generate a new pairing code.
    """
    if not site_name:
        try:
            site_name = get_active_site()
        except FileNotFoundError:
            raise click.ClickException("No active site configured. Use --site to specify one.")

    site_dir = SITES_DIR / site_name
    if not site_dir.exists():
        raise click.ClickException(f"No local config found for '{site_name}'.")

    action = "revoke the server token AND remove" if revoke else "remove"
    if not Confirm.ask(
        f"[yellow]{action.capitalize()}[/yellow] local config for [bold]{site_name}[/bold]?",
        default=False,
    ):
        console.print("Cancelled.")
        return

    if revoke:
        try:
            from cli.lib.config import load_local_config
            from cli.lib.http import WrsClient

            local_config = load_local_config(site_name)
            client = WrsClient(local_config)
            client.request("POST", "/connect/revoke", payload={})
            console.print("[green]Server token revoked.[/green] The plugin API is now disabled server-side.")
        except Exception as exc:
            console.print(
                f"[yellow]Could not revoke server token ({exc}).[/yellow] Removing local config anyway."
            )

    shutil.rmtree(site_dir, ignore_errors=True)

    # Update the active-site pointer if we just removed the active site.
    try:
        current_active = ACTIVE_SITE_FILE.read_text(encoding="utf-8").strip() if ACTIVE_SITE_FILE.exists() else ""
        if current_active == site_name:
            remaining = list_sites()
            if remaining:
                set_active_site(remaining[0])
                console.print(f"Active site switched to: [bold]{remaining[0]}[/bold]")
            else:
                ACTIVE_SITE_FILE.unlink(missing_ok=True)
                console.print("No remaining sites. Run the setup wizard to add one.")
    except Exception:
        pass

    console.print(f"[green]Disconnected:[/green] {site_name}")
